**This notebook is an exercise in the [Pandas](https://www.kaggle.com/learn/pandas) course.  You can reference the tutorial at [this link](https://www.kaggle.com/residentmario/creating-reading-and-writing).**

---

In [1]:
import sys
sys.version

'3.7.9 | packaged by conda-forge | (default, Feb 13 2021, 20:03:11) \n[GCC 9.3.0]'

# Introduction

The first step in most data analytics projects is reading the data file. In this exercise, you'll create Series and DataFrame objects, both by hand and by reading data files.

Run the code cell below to load libraries you will need (including code to check your answers).

In [2]:
import pandas as pd
pd.set_option('max_rows', 5)
from learntools.core import binder; binder.bind(globals())
from learntools.pandas.creating_reading_and_writing import *
print("Setup complete.")

Setup complete.

# Exercises

## 1.

In the cell below, create a DataFrame `fruits` that looks like this:

![](https://i.imgur.com/Ax3pp2A.png)

In [4]:
fruits = pd.DataFrame([[30,21]], columns = ['Apples','Bananas'])
fruits

   Apples  Bananas
0      30       21

In [9]:
# Your code goes here. Create a dataframe matching the above diagram and assign it to the variable fruits.
fruits = pd.DataFrame({'Apples' : [30], 'Bananas' : [21]})

# Check your answer
q1.check()
fruits

Correct

   Apples  Bananas
0      30       21

In [ ]:
#q1.hint()
#q1.solution()

## 2.

Create a dataframe `fruit_sales` that matches the diagram below:

![](https://i.imgur.com/CHPn7ZF.png)

In [8]:
# Your code goes here. Create a dataframe matching the above diagram and assign it to the variable fruit_sales.
fruit_sales = pd.DataFrame({'Apples' : [35, 41], 'Bananas' : [21, 34]},
                           index = ['2017 Sales', '2018 Sales'])

# Check your answer
q2.check()
fruit_sales

Correct

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

In [ ]:
#q2.hint()
#q2.solution()

## 3.

Create a variable `ingredients` with a Series that looks like:

```
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object
```

In [6]:
ingredients =  pd.Series(['4 cups','1 cup','2 large','1 can'],
                         index = ['Flour','Milk','Eggs','Spam'],
                         name = 'Dinner')

# Check your answer
q3.check()
ingredients

Correct

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [7]:
#q3.hint()
#q3.solution()

## 4.

Read the following csv dataset of wine reviews into a DataFrame called `reviews`:

![](https://i.imgur.com/74RCZtU.png)

The filepath to the csv file is `../input/wine-reviews/winemag-data_first150k.csv`. The first few lines look like:

```
,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,"This tremendous 100% varietal wine[...]",Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and[...]",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,,Tinta de Toro,Bodega Carmen Rodríguez
```

In [36]:
!pwd #현재위치 확인
# %cd는 이동
# !ls -l 은 대상 폴더 안의 디렉토리 확인

/kaggle/input/wine-reviews

In [24]:
%cd ../

/kaggle

In [25]:
!ls -l

total 12
drwxr-xr-x 12 root root 4096 Jun  7 04:16 input
drwxr-xr-x  3 root root 4096 Jun  7 04:16 lib
drwxr-xr-x  2 root root 4096 Jun  7 04:16 working

In [26]:
%cd input

/kaggle/input

In [27]:
!ls -l

total 0
drwxr-xr-x 2 nobody nogroup 0 Dec  3  2020 188-million-us-wildfires
drwxr-xr-x 2 nobody nogroup 0 Dec  3  2020 chess
drwxr-xr-x 2 nobody nogroup 0 Dec  3  2020 kepler-exoplanet-search-results
drwxr-xr-x 2 nobody nogroup 0 Dec  3  2020 pitchfork-data
drwxr-xr-x 2 nobody nogroup 0 Dec  3  2020 powerlifting-database
drwxr-xr-x 8 nobody nogroup 0 Dec  3  2020 publicassistance
drwxr-xr-x 2 nobody nogroup 0 Dec  3  2020 ramen-ratings
drwxr-xr-x 3 nobody nogroup 0 Dec  3  2020 things-on-reddit
drwxr-xr-x 2 nobody nogroup 0 Dec  3  2020 wine-reviews
drwxr-xr-x 2 nobody nogroup 0 Dec  3  2020 youtube-new

In [28]:
%cd wine-reviews

/kaggle/input/wine-reviews

In [31]:
# 데이터위치를 상위폴더에서 지정할 때 reviews = pd.read_csv('../input/wine-reviews/winemag-data_first150k.csv', index_col = 0)
# 데이터 위치의 폴더로 위처럼 이동 시켜서 불러올 때
reviews = pd.read_csv('winemag-data_first150k.csv', index_col = 0)
# Check your answer
q4.check()
reviews

Correct

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
...,...,...,...,...,...,...,...,...,...,...
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

In [ ]:
#q4.hint()
#q4.solution()

## 5.

Run the cell below to create and display a DataFrame called `animals`:

In [37]:
!pwd #원래 자리로 돌려놓음

/kaggle/input/wine-reviews

In [38]:
%cd ../..

/kaggle

In [39]:
%cd working

/kaggle/working

In [40]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19

In the cell below, write code to save this DataFrame to disk as a csv file with the name `cows_and_goats.csv`.

In [43]:
animals['Cows'][0]

12

In [44]:
animals.index

Index(['Year 1', 'Year 2'], dtype='object')

In [48]:
animals[:1]

        Cows  Goats
Year 1    12     22

In [50]:
animals[1:2]

        Cows  Goats
Year 2    20     19

In [54]:
# Your code goes here
animals.to_csv('cows_and_goats.csv')
# Check your answer
q5.check()

Correct

In [61]:
!ls -l

total 8
---------- 1 root root 263 Jun  7 04:16 __notebook_source__.ipynb
-rw-r--r-- 1 root root  38 Jun  7 05:15 cows_and_goats.csv

In [60]:
pd1 = pd.read_csv('cows_and_goats.csv', index_col = 0)
pd1

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [42]:
#q5.hint()
#q5.solution()

# Keep going

Move on to learn about **[indexing, selecting and assigning](https://www.kaggle.com/residentmario/indexing-selecting-assigning)**.

---




*Have questions or comments? Visit the [Learn Discussion forum](https://www.kaggle.com/learn-forum/161299) to chat with other Learners.*